### ISSUE TITLE
Logo for SystemXVI

### ISSUE THREAD

**Issue by Xwhn** [ServiceManager/ServiceManager#1]
On your request I've created a logo for SystemXVI project. I can send its project file.

![system16_logo_512](https://cloud.githubusercontent.com/assets/8299732/9645543/ee1c36d4-51d4-11e5-87a0-2fec9cda3ea2.png)

**Comment by freelinuxfromsystemd** [comment]
Thank you very much - this is fantastic. I would appreciate the project file, yes.

Let me know if you have a Bitcoin or Dogecoin address - I'd like to offer something for your effort.

**Comment by Xwhn** [comment]
It is an only gift for your fantastic work bro. Thank you. 
There are .png, .ai, .eps files in the .rar file, from 128px to 16px: http://1drv.ms/1VzXfBq
