### ISSUE TITLE
Better license?

### ISSUE THREAD

**Issue by cb88** [ServiceManager/ServiceManager#10]
GPLv3 seems to me like the very worst license for this particular project?

From what I've ready of people's opinions online ... It seems to be that you'd want this to be BSD/MIT or dual licensed MIT and GPLv2. Or something like that.. None of the operating system projects you list use or have any particular love of the GPLv3 license as far as I know.

If I'm just being annoying and you really love the GPLv3 then never mind me :)

**Comment by JX7P** [comment]
No worries, you're not being annoying.

In fact, my preference is actually for licences that incorporate mandatory reciprocation from for-profit entities to the commons. That'd be a project killer, of course, so it's not an option.

With a lot of interest coming from the BSD world it seems that a more liberal licence would be prudent. I'll be applying one in the next few moments.

**Comment by tebruno99** [comment]
JX7P,  Good call.  If cross platform is truly a goal of the lowest level services a bsd compat license would be required.

**Comment by JX7P** [comment]
BSD licence adopted with commit 043b756

**Comment by TheDharc** [comment]
or maybe a MPL-like licenses. it's copyleft too, but FreeBSD, NetBSD and DragonflyBSD can use.
