### ISSUE TITLE
Is there anywhere someone can learn the ins and outs of this init system? 

### ISSUE THREAD

**Issue by thagabe** [ServiceManager/ServiceManager#11]
I'm interested in this project because of the muslib+Busybox support. What is the status of this project and how can i learn in detail this project. Have you guys ported this to embedded (Openwrt)? 

All the best

**Comment by uselessd** [comment]
The README makes it clear the project is not yet functional (in the sense that you can boot from it). It's a WIP, though evolving quite quickly.

Architecture so far is described in doc/. There's a flow chart and a textual description. More to come as things are ironed out.

OpenWrt use their own system called procd, from what I remember. Nominally, it should be possible for SystemXVI to run as a service manager on any GNU or not-so-GNU/Linux.

**Comment by thagabe** [comment]
Thanks, I'll read up on the docs.
