### ISSUE TITLE
Which format log files will have? Binary or text? 

### ISSUE THREAD

**Issue by vasili111** [ServiceManager/ServiceManager#13]
Which format log files will have? Binary or text?

**Comment by JX7P** [comment]
Text. I'm quite favourable towards the idea of using rsyslog here.

**Comment by uselessd** [comment]
Logging is a complete red herring. You will be using some log aggregation and indexing application or service for any large workloads where it is of paramount importance.

The service manager should probably just leave it at doing some basic export and rotation of logs on a per-application basis, fit for further processing by the user. Nothing more complicated than daemontools.
