### ISSUE TITLE
Write a backend for process-tracker using the Linux cn_proc netlink connector

### ISSUE THREAD

**Issue by JX7P** [ServiceManager/ServiceManager#15]
process-tracker implements a simple and generic interface for tracking processes. It registers whatever events it needs to monitor with the KQueue provided to it, and is called after each KEvent received to check for a message and return an appropriate structure if so - that is, if a PID in its watch list exits, or if a child appears for a PID in its watch list. It automatically registers the child, if it should appear, for monitoring, and deregisters a PID in its watch list that exits.

Currently a KEvent backend exists using EVFILT_PROC. This could be quite simply implemented using the cn_proc netlink connector in Linux, and this should be done.

**Comment by uselessd** [comment]
You already had one for systemdr before you deprecated that, right? Just copy it over, with a few adjustments to make it purely C.

**Comment by JX7P** [comment]
Done in 13a5f3c.
