### ISSUE TITLE
check return values of malloc

### ISSUE THREAD

**Issue by hardening** [ServiceManager/ServiceManager#17]
I noticed that mallocs return values are never checked which looks quite bad for an init program...

**Comment by JX7P** [comment]
Personally I'm sceptical of the value of checking malloc()'s return value, given that memory overcommit means that even a seemingly-valid pointer may not be usable.

Having said that, I will attempt to make sure henceforth, and work on those parts that are yet incapable of handling so, that should malloc() return 0 there will not be a crash (where possible).

An additional note: the PID 1 component of S16 is as yet unwritten, but I will probably adapt sinit for that purpose. I've not yet reviewed the possibility thoroughly, but ideally, I do not want any dynamic memory allocation in there.

**Comment by JX7P** [comment]
I'd like to propose an alternative idea:

* restartd allocates a small emergency memory pool at start
* malloc calls are replaced with calls to a safe malloc that tries to malloc(); if it fails, it returns a pointer to some area in the emergency pool, and sets a flag in restartd's manager object indicating low-memory state
* restartd can continue to perform essential functions but the ability to import units amongst other things is disabled

**Comment by JX7P** [comment]
I have incorporated the above idea using Eli Bendersky's `memmgr`. I will be moving towards its use and implementing the emergency callbacks as described above.
