### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ServiceManager/ServiceManager#19]
I would like to point out that identifiers like "[`_STORAGE_H_`](https://github.com/ServiceManager/ServiceManager/blob/4c2af53388c4589a04f70b7d10618cb0b01db763/app/repositoryd/storage.h#L1)" and "[`__SVCCFG_H__`](https://github.com/ServiceManager/ServiceManager/blob/4c2af53388c4589a04f70b7d10618cb0b01db763/app/svccfg/svccfg.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
I suggest also to [reconsider the usage of double underscores](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") in affected identifiers.

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/ServiceManager/ServiceManager/blob/4c2af53388c4589a04f70b7d10618cb0b01db763/lib/s16db/translate.h#L1 "Update candidate") left over?

**Comment by JX7P** [comment]
Whoops - that file should have been deleted a while ago. I've also removed the double underscores where they were found.

**Comment by elfring** [comment]
Which commit will contain corresponding source file adjustments?

**Comment by JX7P** [comment]
The corrections were in 1c73940a

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/ServiceManager/ServiceManager/commit/1c73940a6374e0b9d7b57e21373200a9fbe15211#diff-82f67b93f200b577d6e672d3f2692f81L1 "Deletion of a few underscores").
