### ISSUE TITLE
American vs British English

### ISSUE THREAD

**Issue by mkfifo** [ServiceManager/ServiceManager#25]
I have noticed that the documentation appears to be using British English ('Serialisation' over 'Serialization').

I was wondering if all code should also be in British English? Or should the code and documentation use American English?

**Comment by JX7P** [comment]
I prefer British English in both code and documentation.

**Comment by Megaf** [comment]
I would also prefer the British English, it's also not actually British, but the English spoken everywhere but USA.

**Comment by mkfifo** [comment]
I was only using the term 'British English' as that is where the language originated (everywhere else that speaks it is generally a ex-colony), I prefer British English but wanted to check.

I may try write a coding / contributing guideline document that mentions this and #26

**Comment by Megaf** [comment]
Thanks mkfifo.
