### ISSUE TITLE
Relation with uselessd?

### ISSUE THREAD

**Issue by gdm85** [ServiceManager/ServiceManager#31]
Do you guys know about [uselessd](https://bitbucket.org/Tarnyko/uselessd), right?

It started as a joke, but I think some code was pretty usable there.

Has anybody considered giving a look / importing some code?

**Comment by uselessd** [comment]
I am the uselessd guy. There is no relation, and there is nothing of relevance.

**Comment by gdm85** [comment]
@uselessd glad you're following :) what do you mean by "nothing of relevance"? as in, there is nothing this project could borrow from uselessd?

**Comment by uselessd** [comment]
What the hell could it?
