### ISSUE TITLE
S16 should be buildable with CMake

### ISSUE THREAD

**Issue by JX7P** [ServiceManager/ServiceManager#7]
Some folk would rather if this could be built with CMake to aid in some less-common use cases and in packaging.

**Comment by uselessd** [comment]
I'd honestly go for a handrolled Makefile, but I suppose a well recognized behemoth like CMake would appease a common denominator. Its quite tolerable to use, admittedly.

**Comment by RomanHargrave** [comment]
As much as I like CMake, it is overkill for a lot of projects.
