### ISSUE TITLE
Confusion about aim of the project

### ISSUE THREAD

**Issue by stanier** [ServiceManager/ServiceManager#8]
No offense, but I can't tell if it's a joke or not

**Comment by uselessd** [comment]
It is not. See: https://news.ycombinator.com/item?id=10212885

There's a flow chart and textual description of the architecture in doc/. It's a serious effort.

**Comment by stanier** [comment]
@uselessd alright cool just checking.  The testimonials section forced me to believe that either the whole thing was a sarcastic joke or the developers just had a really good sense of humour about their critics.  Glad to know it's the latter
